### ISSUE TITLE
Regarding (re)defining characters and the manual.

### ISSUE THREAD

**Issue by Karpeth** [u-fischer/chessboard#10]
"The pieces are named with simple ASCII-chars, so the number of different pieces is restricted.(It is perhaps possible to define piece names consisting of two or more chars, and to use such names by putting braces around the chars e.g., {KK}a3. A small test worked fine for me, but I wouldn’t bet that it really works everywhere.)"

While I never got the {KK} to work, I would like to report that compiling with XeLaTeX, several non-ascii characters work. Tested with greek and coptic.

**Comment by u-fischer** [comment]
Yes, with the unicode engines (most) characters should be fine. Now that utf8 input is protected in pdflatex it could also be that non-ascii works there too (but I didn't check).

**Comment by Karpeth** [comment]
> Yes, with the unicode engines (most) characters should be fine. Now that utf8 input is protected in pdflatex it could also be that non-ascii works there too (but I didn't check).

Tested with pdflatex in texmaker, exact same code throws multiple errors.
