### ISSUE TITLE
backmoves and other commands print in front of pieces on white squares

### ISSUE THREAD

**Issue by Karpeth** [u-fischer/chessboard#13]
Attaching pdf for clarity
[Regler.pdf](https://github.com/u-fischer/chessboard/files/14603805/Regler.pdf)
\documentclass[titlepage,a4paper,oneside]{report}
\usepackage{chessboard}
\begin{document}
\chessboard[smallboard,maxfield=h8,showmover=false,addpieces={Pa3,Pb3,Pc3,Pd3,Pe4,Pf4,Pg4,Ph4,pa5,pb5,pc5,pd5,pe6,pf6,pg6,ph6}, pgfarrow={}, pgfstyle={straightmove},backmoves={a1-h8,a8-h1}]
\end{document}

Produces lines in front of, not behind pieces on white squares when pieces are redefined using masks. If not changing the pieces, it's in front on both black and white squares.

**Comment by u-fischer** [comment]
your pieces do not use a mask, so the inner part is transparent. You need an encoding like LSBC1 instead (I use yellow as it shows better where the line is going)

~~~~
\documentclass[titlepage,a4paper,oneside]{report}
\usepackage{chessboard}
\usepackage[LSBC1,T1]{fontenc}
\begin{document}
\chessboard[smallboard,maxfield=h8,showmover=false,addpieces={Pa3,Pb3,Pc3,Pd3,Pe4,Pf4,Pg4,Ph4,pa5,pb5,pc5,pd5,pe6,pf6,pg6,ph6}, pgfarrow={}, pgfstyle={straightmove},color=yellow,backmoves={a1-h8,a8-h1}]

\chessboard[boardfontencoding=LSBC1,smallboard,maxfield=h8,showmover=false,addpieces={Pa3,Pb3,Pc3,Pd3,Pe4,Pf4,Pg4,Ph4,pa5,pb5,pc5,pd5,pe6,pf6,pg6,ph6}, pgfarrow={}, pgfstyle={straightmove},color=yellow,backmoves={a1-h8,a8-h1}]

\end{document}
~~~~

![image](https://github.com/u-fischer/chessboard/assets/4047173/3bf670ba-7d87-421e-b842-a8a23b8f8c02)

**Comment by Karpeth** [comment]
You are absolutely correct. I am sorry.

I went to recheck the code for redefining the pawns, and I missed adding a mask on white spaces.
