### ISSUE TITLE
[question]about support of crazyhouse chess

### ISSUE THREAD

**Issue by matyapiro31** [u-fischer/chessboard#4]
I'm using this package but I cannot find good way to express pieces on reserve of crazyhouse chess.

**Comment by u-fischer** [comment]
That is not really a chessboard issue. Better ask such questions e.g. at tex.stackexchange.

Draw some tabular or tikzpicture or something like that at the side.

~~~~
\documentclass{article}
\usepackage{chessboard,array}
\begin{document}
\chessboard[setpieces={Ke1,Rd1,kc7,ba8}]
\quad
\extrarowheight15pt
\begin{tabular}[b]{|l|l|}
\hline
\WhiteKnightOnWhite & \BlackQueenOnWhite\\\hline
\WhiteRookOnWhite   &\\\hline
\end{tabular}
\end{document}
~~~~

**Comment by matyapiro31** [comment]
How about crazyhouse FEN?
